# Generated by Django 6.1.1 on 2026-09-12 05:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='ai_prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='duration_seconds',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='hook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='language',
            field=models.CharField(default='Russian', max_length=64),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='promotion_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='recommended_publish_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='telegram_delivery_status',
            field=models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENDING', 'Sending'), ('SENT', 'Sent to Telegram'), ('FAILED', 'Delivery Failed')], default='NOT_SENT', max_length=32),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='video_file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_videos_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duration_seconds',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='Russian', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='niche',
            field=models.CharField(default='AI and technology', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='style',
            field=models.CharField(default='Educational and engaging', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_audience',
            field=models.CharField(default='Beginners', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_linking_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_linking_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID for bot notifications and delivery.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='contentpost',
            constraint=models.UniqueConstraint(fields=('user', 'scheduled_at'), name='unique_user_daily_scheduled_post'),
        ),
    ]
