# Generated by Django 6.1.1 on 2026-09-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentpost_ai_prompt_used_contentpost_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_paid_generation',
            field=models.BooleanField(default=False, help_text='Allow automatic use of paid AI provider credits'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_providers',
            field=models.CharField(default='local,google,openai', help_text='Comma-separated provider order preference', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating Assets'), ('READY_MANUAL', 'Ready for Manual Upload (Fallback)'), ('PUBLISHED', 'Published via API'), ('WAITING_FOR_QUOTA', 'Waiting for Quota Reset'), ('FAILED', 'Generation / Posting Failed')], default='DRAFT', max_length=32),
        ),
        migrations.CreateModel(
            name='AIProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google AI / Veo'), ('openai', 'OpenAI / Sora'), ('runway', 'Runway Gen'), ('local', 'Local Fallback Engine')], default='google', max_length=64)),
                ('external_account_id', models.CharField(blank=True, help_text='Email or unique identifier from OAuth provider', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Connected'), ('EXPIRED', 'Authorization Expired'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Authorization Error')], default='ACTIVE', max_length=32)),
                ('quota_status', models.CharField(choices=[('AVAILABLE', 'Quota Available'), ('EXHAUSTED', 'Quota Exhausted'), ('WAITING_FOR_QUOTA', 'Waiting for Quota Reset')], default='AVAILABLE', max_length=32)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('reset_at', models.DateTimeField(blank=True, help_text='Exact next quota reset time returned by provider API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('request_type', models.CharField(choices=[('SCRIPT', 'Script Generation'), ('SCENE', 'Scene Breakdown'), ('VIDEO', 'Video Generation'), ('AUDIO', 'Audio TTS'), ('RENDER', 'Final Render')], default='VIDEO', max_length=32)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('WAITING_FOR_QUOTA', 'Waiting for Quota'), ('QUOTA_EXCEEDED', 'Quota Exceeded')], default='SUCCESS', max_length=32)),
                ('external_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='core.aiprovideraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
